name: Deploy Hugo site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      # 检查构建内容
      - name: Check build output
        run: |
          echo "公共目录大小:"
          du -sh public/
          echo "最大的10个文件:"
          find public/ -type f -exec du -h {} \; | sort -rh | head -n 10
          echo "目录结构:"
          find public/ -type d | sort

      - name: Process public directory
        run: |
          cd public
          # 查找并移除符号链接
          find . -type l -delete
          # 确保权限正确
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4