name: Deploy Hugo site to gh-pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write  # 需要写入权限来推送gh-pages分支

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # 获取完整历史记录以便操作gh-pages分支

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      # 检查构建内容
      - name: Check build output
        run: |
          echo "公共目录大小:"
          du -sh public/
          echo "最大的10个文件:"
          find public/ -type f -exec du -h {} \; | sort -rh | head -n 10
          echo "目录结构:"
          find public/ -type d | sort

      - name: Process public directory
        run: |
          cd public
          # 查找并移除符号链接
          find . -type l -delete
          # 确保权限正确
          find . -type f -exec chmod 644 {} \;
          find . -type d -exec chmod 755 {} \;

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
          force_orphan: true  # 确保每次都是全新部署，不保留历史
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

  notify-server:
    needs: build  # 依赖构建job
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Remote Command
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.SSH_PORT || '22' }} \
              ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
              "/opt/deploy-hugo.sh"
